name: bmi_calculator
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  font_awesome_flutter: ^9.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  flutter_launcher_name: "^0.0.1"

flutter_launcher_name:
  name: "BMI Calculator"


flutter:
  uses-material-design: true
  # assets:
  #   - assets/fonts/

  # fonts:
  # - family: K2D
  #   fonts:
  #     - asset: fonts/K2D-Regular.ttf
  #     - asset: fonts/K2D-Light.ttf
  #       weight: 300
  #     - asset: fonts/K2D-Bold.ttf
  #       weight: 900